modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="dimesionaddons"
version="1.0.0"
displayName="dimesionaddons"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="kryst, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dimesionaddons]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.dimesionaddons]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.dimesionaddons]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.dimesionaddons.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration